databases:
  - name: quote_manager_db_new
    databaseName: quote_manager_new
    user: quote_manager_user_new
    plan: free

services:
  - type: web
    name: quote_manager
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quote_manager_db_new
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    autoDeploy: true
